ghanaman/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
# from django.contrib.auth.views import login
from index.utils import anonymous_required
from django.conf import settings
from index.views import login_custom

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ghanaman.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('userprofile.urls')),
    url(r'^', include('topics.urls')),
    url(r'^', include('index.urls')),
    url(r'^advertise/', include('advertises.urls')),
    url(r'^tracking/', include('tracking.urls')),
    # url(r'^login/$', anonymous_required(login), {'template_name': 'login.html'}),
    url(r'^login/$', login_custom),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)


if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	)

index/urls.py
from django.conf.urls import patterns, url

from index.views import main_page, register, thanks_register, confirm_register, search, newtopics,\
						recent, trending, login_without_password, entry_code_login
from index.utils import anonymous_required

urlpatterns = patterns('',
 	url(r'^$', main_page, name='main_page'),
    url(r'^register/$', anonymous_required(register), name='register'),
    url(r'^register/thanks/$', thanks_register, name='register_thanks'),
    url(r'^register/confirm/([\w\+@/. ]+)/(\w+)$', anonymous_required(confirm_register), name='register_confirm'),
	url(r'^search/$', search, name='search'),
	url(r'^metions/$', search, name='metions'),
	url(r'^newtopics/$', newtopics, name='newtopics'),
	url(r'^recent/$', recent, name='recent'),
	url(r'^trending/$', trending, name='trending'),
	url(r'^login_without_password/$', login_without_password, name='login_without_password'),
	url(r'^entry_code_login/$', entry_code_login, name='entry_code_login'),
)

userprofile/urls.py
from django.conf.urls import patterns, url
from userprofile.views import profile, profile_edit, email_change, follow_board, followed_boards, \
	follow_topic, followed_topics, likes, like_topics, shares, share_topics, follow_member, \
	followers, followings, likes_and_shares, shared
from userprofile.views import send_email_message, send_confirmation_email_for_account_deactivation, \
    do_confirmation_email_for_account_deactivation, deactivate_account, send_mail_to_supermod

urlpatterns = patterns('',
    url(r'^email/change/$', email_change, name='email_change'),
    url(r'^profile/([\w\+/. ]+)$', profile, name='profile'),
    url(r'^profile_edit/$', profile_edit, name='profile_edit'),
	url(r'^profile/sendmail/([\w\+/. ]+)/$', send_email_message, name='send_email_message'),
	url(r'^follow_board/(?P<board_id>\d+)/$', follow_board, name='follow_board'),
    url(r'^followed_boards/$', followed_boards, name='followed_boards'),
    url(r'^follow_topic/(?P<topic_id>\d+)/$', follow_topic, name='follow_topic'),
    url(r'^followed_topics/$', followed_topics, name='followed_topics'),
    url(r'^likes/(?P<comment_id>\d+)/$', likes, name='likes'),
    url(r'^like_topics/$', like_topics, name='like_topics'),
    url(r'^shares/(?P<comment_id>\d+)/$', shares, name='shares'),
    url(r'^share_topics/$', share_topics, name='share_topics'),
    url(r'^follow_member/(?P<profile_id>\d+)/$', follow_member, name='follow_member'),
    url(r'^followers/$', followers, name='followers'),
    url(r'^followings/$', followings, name='followings'),
    url(r'^likes_and_shares/$', likes_and_shares, name='likes_and_shares'),
    url(r'^shared/$', shared, name='shared'),
    url(r'^send_confirmation_email_for_account_deactivation/$', send_confirmation_email_for_account_deactivation, name='send_confirmation_email_for_account_deactivation'),
    url(r'^do_confirmation_email_for_account_deactivation/$', do_confirmation_email_for_account_deactivation, name='do_confirmation_email_for_account_deactivation'),
    url(r'^deactivate_account/(?P<code>\w+)$', deactivate_account, name='deactivate_account'),
    url(r'^sendmailtosupermod/(?P<board_id>\d+)$', send_mail_to_supermod, name='send_mail_to_supermod'),
)

userprofile/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from topics.models import Comment

# Create your models here.
		
class UserProfile(models.Model):
	# gender choices
	GENDER_CHOICES = (('M','Male'), ('F','Female'))
	# type moderator choices
	MOD_TYPE = (
			('0', 'Normal'),
			('1', 'Super Mod'), 
			('2', 'Mod')
		)
	# variable use to store year old of user
	age = 0

	user = models.OneToOneField(User, related_name="profile")
	date_of_birth = models.DateField(_('Date of birth'), blank = True, null = True)
	gender = models.CharField(_('Gender'), max_length=1, blank=False, null = True, choices = GENDER_CHOICES, default = None)
	personal_text = models.CharField(max_length=255, null=True, blank=True)
	signature = models.CharField(max_length=255, null=True, blank=True)
	avatar = models.ImageField(upload_to = 'avatar', blank = True, null = True)
	website_title = models.CharField(max_length=255, null=True, blank=True)
	website_url = models.URLField(max_length=255, null=True, blank=True)
	location = models.CharField(max_length=255, null=True, blank=True)
	yim = models.CharField(max_length=255, null=True, blank=True)
	twitter = models.CharField(max_length=255, null=True, blank=True)
	followed_boards = models.ManyToManyField('topics.TopicCategory', null=True, blank=True, related_name="profile_followed_boards")
	followed_topics = models.ManyToManyField('topics.Topic', null=True, blank=True, related_name="profile_followed_topics")
	mod_type = models.CharField(_('Mod Type'), max_length=1, blank=False, null = True, choices = MOD_TYPE, default = 0)
	mod_category = models.ManyToManyField('topics.TopicCategory', null=True, blank=True)
	code = models.CharField(max_length=200, blank=True, null=True)
	deactived = models.BooleanField(blank=True, default=0)

	def __str__(self):  
		return "%s's profile" % self.user

def create_user_profile(sender, instance, created, **kwargs):  
	if created:  
		profile, created = UserProfile.objects.get_or_create(user=instance)  

post_save.connect(create_user_profile, sender=User)

class EmailMessage(models.Model):
	sender = models.IntegerField()
	receiver = models.IntegerField()
	is_read = models.IntegerField(default=0)
	send_again = models.BigIntegerField(default=None)


class Follow(models.Model):
	follower = models.ForeignKey(UserProfile, related_name='profile_follower') # profile is followed
	following = models.ForeignKey(UserProfile, related_name='profile_following') # profile follows
	date = models.DateTimeField(default=timezone.now)


class Like(models.Model):
	user = models.ForeignKey(User, related_name='user_like')
	comment = models.ForeignKey(Comment, related_name='comment_like')
	date = models.DateTimeField(default=timezone.now)


class Share(models.Model):
	user = models.ForeignKey(User, related_name='user_share')
	comment = models.ForeignKey(Comment, related_name='comment_share')
	date = models.DateTimeField(default=timezone.now)

userprofile/views.py
import json
import time
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from userprofile.forms import EditProfileForm, ChangeEmailForm, FollowBoardForm, SendMailToSuperMod
from userprofile.models import UserProfile, EmailMessage, Follow, Like, Share
from index.models import Register
from tracking.models import Visitor
from topics.models import Topic, TopicCategory, Comment
from advertises.views import get_random_advertises

from index.utils import generate_token
from index.views import page_not_found

# Create your views here.
@login_required
def profile_edit(request):
	# if this is a POST request we need to process the form data
	profile = UserProfile.objects.get(user_id=request.user.id)
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = EditProfileForm(request.POST, request.FILES, instance=profile)
		# check whether it's valid:
		if form.is_valid():
			# save information
			form.save()
			return HttpResponseRedirect('/profile/' + str(request.user.username))

	# if a GET (or any other method) we'll create a blank form
	else:
		form = EditProfileForm(instance=profile)

	return render(request, 'profile_edit.html', {'form': form})

@login_required
def profile(request, username):
	user =  User.objects.get(username=username)

	profile = UserProfile.objects.get(user_id=user.id)
	visitors = Visitor.objects.filter(user_id=user.id)

	time_spent = 0

	for visitor in visitors:
		time_spent = time_spent + visitor.time_on_site

	if Follow.objects.filter(follower=request.user.profile, following=profile):
		is_followed = True
	else:
		is_followed = False

	if Follow.objects.filter(follower=profile, following=request.user.profile):
		is_follow = True
	else:
		is_follow = False

	return render(request, 'profile.html', {
			'Currentuser' : user, 
			'profile' : profile, 
			'time_spent' : time.strftime('%H:%M:%S', time.gmtime(float(time_spent))),
			'is_followed': is_followed,
			'is_follow': is_follow,
		})


@login_required
def email_change(request):
	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = ChangeEmailForm(request.POST, instance=request.user)
		# check whether it's valid:
		if form.is_valid():
			# update register again
			user =  User.objects.get(id=request.user.id)
			register = Register.objects.get(email=user.email)
			register.email = form.cleaned_data['email']
			register.save()

			# save information
			form.save()
			return HttpResponseRedirect('/profile_edit')

	# if a GET (or any other method) we'll create a blank form
	else:
		form = ChangeEmailForm(instance=request.user)

	return render(request, 'email_change.html', {'form': form})

@login_required
def follow_board(request, board_id):
	try:
		board = TopicCategory.objects.get(pk=board_id)
	except TopicCategory.DoesNotExist:
		return page_not_found(request)

	if request.method == 'POST':
		user = User.objects.get(pk=request.user.id)
		profile = UserProfile.objects.get(user=user)
		if request.POST.get('follow') == 'true':
			profile.followed_boards.add(board)
			follow = True
		else:
			profile.followed_boards.remove(board)
			follow = False

		return HttpResponse(json.dumps({"success": True, "follow": follow}))
	return HttpResponse(json.dumps({"success": False}))

@login_required
def followed_boards(request):
	user = User.objects.get(pk=request.user.id)
	profile = UserProfile.objects.get(user=user)

	sort = request.GET.get('sort')

	if request.method == 'POST':
		board_id = request.POST.get('followed_boards')
		board = TopicCategory.objects.get(pk=int(board_id))
		profile.followed_boards.add(board)
		
		return HttpResponseRedirect('/followed_boards')
	else:
		form = FollowBoardForm(instance=profile)
	if sort == 'create_time':
		topics_list = Topic.objects.filter(category__in=profile.followed_boards.all()).order_by('-date')
	elif sort == 'update_time':
		topics_list = Topic.objects.filter(category__in=profile.followed_boards.all()).order_by('-updated_at')
	else:
		topics_list = Topic.objects.filter(category__in=profile.followed_boards.all()).order_by('-date')
		

	for topic in topics_list:
		topic.last_comment = topic.comment_topic.all().reverse()[0]
	paginator = Paginator(topics_list, settings.NUMBER_ITEM_PERPAGE)

	page = request.GET.get('page')
	try:
		topics = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		topics = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		topics = paginator.page(paginator.num_pages)

	# list of advertises
	advertises = get_random_advertises()

	return render(request, "topics.html", {	
											'title': 'Followed Boards',
											'topics': topics,
											'follow': True,
											'form': form,
											'profile': profile,
											'advertises': advertises,
											})

@login_required
def follow_topic(request, topic_id):
	try:
		topic = Topic.objects.get(pk=topic_id)
	except Topic.DoesNotExist:
		return page_not_found(request)

	if request.method == 'POST':
		user = User.objects.get(pk=request.user.id)
		profile = UserProfile.objects.get(user=user)
		if request.POST.get('follow') == 'true':
			profile.followed_topics.add(topic)
			follow = True
		else:
			profile.followed_topics.remove(topic)
			follow = False

		return HttpResponse(json.dumps({"success": True, "follow": follow}))
	return HttpResponse(json.dumps({"success": False}))

@login_required
def followed_topics(request):
	user = User.objects.get(pk=request.user.id)
	profile = UserProfile.objects.get(user=user)

	topics_list = profile.followed_topics.all().order_by('-date')
	for topic in topics_list:
		topic.last_comment = topic.comment_topic.all().reverse()[0]
	paginator = Paginator(topics_list, settings.NUMBER_ITEM_PERPAGE)

	page = request.GET.get('page')
	try:
		topics = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		topics = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		topics = paginator.page(paginator.num_pages)

	# list of advertises
	advertises = get_random_advertises()

	return render(request, "topics.html", {	
											'title': 'Followed Topics',
											'topics': topics,
											'profile': profile,
											'follow_topic': True,
											'advertises': advertises,
											})
@login_required
def send_email_message(request, username):
	user =  User.objects.get(username=username)
	currentUser = User.objects.get(id=request.user.id)
	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		if user.id != request.user.id:

			# send mail
			recipients = user.email
			subject = 'Ghanaman - ' + currentUser.username + ' would like to send you a message'
			
			message = currentUser.username + " would like to send you an email message, but since you're not connected, you'll need to contact " + currentUser.username + " by replying this email.\n\n\n Regards, \n Ghanaman Team, \n For: http://www.ghanaman.com/" + currentUser.username
			
			try:
				# send confirmation email
				send_mail(subject, message, currentUser.email, [recipients])
				# save register information
				reg = EmailMessage(sender=currentUser.id, receiver=user.id)
				reg.save()

			except Exception as e:
				print e

			return render(request, 'sent.html', {'receiver' : user.username})
		else:
			return render(request, 'cannotsend.html')

	return render(request, 'sendmail.html', {'sender' : currentUser.username, 'receiver' : user.username})

@login_required
def likes(request, comment_id):
	try:
		comment = Comment.objects.get(pk=comment_id)
	except Comment.DoesNotExist:
		return page_not_found(request)

	if request.method == 'POST':
		user = User.objects.get(pk=request.user.id)
		if request.POST.get('like') == 'true':
			if not Like.objects.filter(user=user, comment=comment):
				like = Like()
				like.user = user
				like.comment = comment
				like.save()
			like = True
		else:
			like = Like.objects.get(user=user, comment=comment)
			like.delete()
			like = False
		likes = Like.objects.filter(comment=comment).count()

		return HttpResponse(json.dumps({"success": True, "like": like, "likes": likes}))
	return HttpResponse(json.dumps({"success": False}))

@login_required
def like_topics(request):
	user = User.objects.get(pk=request.user.id)
	likes = Like.objects.filter(user=user).order_by('-date').values('comment')
	comments = Comment.objects.filter(id__in=likes)
	for comment in comments:
		comment.likes = Like.objects.filter(comment=comment).count()
		comment.is_liked = Like.objects.filter(comment=comment, user=user)
		comment.shares = Share.objects.filter(comment=comment).count()
		comment.is_shared = Share.objects.filter(comment=comment, user=user)

	paginator = Paginator(comments, settings.NUMBER_ITEM_PERPAGE)

	page = request.GET.get('page')
	try:
		comments = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		comments = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		comments = paginator.page(paginator.num_pages)

	return render(request, "comments.html", {	
											'title': 'My Liked Posts',
											'comments': comments,
											'profile': profile,
											'breadcrum': {'link': 'like_topics', 'title': 'My Liked Posts'}
											})

@login_required
def shares(request, comment_id):
	try:
		comment = Comment.objects.get(pk=comment_id)
	except Comment.DoesNotExist:
		return page_not_found(request)

userprofile/templates/cannotsend.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  <h2>You can't send to yourself</h2>
		</div>
	</div>
{% endblock %}

userprofile/templates/deactivate_account.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
			<h2>Deactivate account</h2>
			<h6 style="color: red">THIS IS A PERMANENT OPERATION AND CANNOT BE REVERSED BY ANYONE, NOT EVEN THE ADMIN.</h6>
			<form action="{% url 'deactivate_account' code %}" method="POST">
				<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
				<input type="hidden" name="confirmed" value="1">
				<input type="submit" value="Deactivate Account">
			</form>
		</div>
	</div>
{% endblock %}

userprofile/templates/do_confirmation_email_for_account_deactivation.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  	<h2>A confirmation email has been sent to your email address. Please follow the link to continue the process.</h2>
		</div>
	</div>
{% endblock %}

userprofile/templates/email_change.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  <h2>Change Email</h2>
		  <div class="board">
		    <div class="board-content board-content-odd board-content-last text-center">
				<form action="{% url 'email_change' %}" method="post" class="form-inline no-margin-bottom"> 
					{% csrf_token %}
					{{ form.non_field_errors }}

					<div class="form-group">
						{{ form.email.label_tag }}
						{{ form.email }}
						{% for error in form.email.errors %} {{ error }} {% endfor %}
					</div>
					
					<input type="submit" value="Submit">
				</form>
		    </div>
		  </div>
		</div>
	</div>
{% endblock %}

userprofile/templates/followers.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}

{% block title %}{{title}}{% endblock title %}

{% block title_and_breadcrums %}
	<h2>{{title}}</h2>
	<div class="board">
		<a href="/"><b>Ghanaman Forum</b></a> /
		<a href="{% url 'followers' %}"><b>Followers</b></a>
	</div>
{% endblock title_and_breadcrums %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="board">
			<div class="text-center">
				<div class="pagination">
					<span class="step-links">
						{% for num in followers.paginator.page_range %}
							{% ifequal num followers.number %}
								<span class="current"><b>({{ num }})</b></span>
							{% else %}
								<a href="?page={{ num }}">({{ num }})</a>
							{% endifequal %} 
						{% endfor %}

						(of <b>{{ followers.paginator.num_pages }}</b> page{{followers.paginator.num_pages|pluralize}})
					</span>
				</div>
			</div>
			{% if followers %}
				{% for follower in followers %}
					<div class="board-content {% cycle 'board-content-odd' 'board-content-even' %} {% if forloop.last %}board-content-last{% endif %} {% if forloop.first %}board-content-first{% endif %}">
						<p class="no-margin-bottom">
							<a href="{% url 'profile' follower.following.user.username %}" class="user">{{follower.following.user.username}}</a>
							{% if follower.follow %}
								(<a href="{% url 'follow_member' follower.following.id %}" class="follow-member" follow-member="false">Un-Follow</a>)
							{% else %}
								(<a href="{% url 'follow_member' follower.following.id %}" class="follow-member" follow-member="true">Follow Back</a>)
							{% endif %}
						</p>
					</div>
				{% endfor %}
			{% else %}
				<div class="board-content board-content-even board-content-first board-content-last">
					<p class="no-margin-bottom text-center">You have no followers at this time</p>
				</div>
			{% endif %}
			
			<div class="text-center">
				<div class="pagination pagination-bottom">
					<span class="step-links">
						{% for num in followers.paginator.page_range %}
							{% ifequal num followers.number %}
								<span class="current"><b>({{ num }})</b></span>
							{% else %}
								<a href="?page={{ num }}">({{ num }})</a>
							{% endifequal %} 
						{% endfor %}

						(of <b>{{ followers.paginator.num_pages }}</b> page{{followers.paginator.num_pages|pluralize}})
					</span>
				</div>
			</div>
		</div>
	</div>
</div>
	
{% endblock %}

{% block script %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('.follow-member').click(function(e) {
				e.preventDefault();
				self = $(this);
				$.ajax({
					type : 'POST',
					data: {csrfmiddlewaretoken: '{{ csrf_token }}', follow_member: self.attr('follow-member')},
					url : self.attr('href'),
					success: function(response){
						response = $.parseJSON(response);
						if (response.success) {
							if (response.follow_member)
								self.text('Un-Follow').attr('follow-member', 'false');
							else
								self.text('Follow Back').attr('follow-member', 'true');
						}
					}
				});
			});
		});
	</script>
{% endblock %}

userprofile/templates/invalidcode.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  	<h2>Invalid Code</h2>
		</div>
	</div>
{% endblock %}

userprofile/templates/profile_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
			<form action="{% url 'profile_edit' %}" method="post" class="no-margin-bottom form-inline form-md form-edit-profile" enctype="multipart/form-data"> 
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="board-content board-content-even text-center board-content-first">
					<div class="form-group">
						<label>Email:</label>
						{{ user.email }}
						<a href="{% url 'email_change' %}">Change Email</a>
					</div>
				</div>
				<div class="board-content board-content-odd text-center">
					<div class="form-group">
						{{ form.date_of_birth.label_tag }}
						{{ form.date_of_birth|addclass:"form-control" }}
						<p class="error no-margin-bottom">
							{% for error in form.date_of_birth.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center">
					<div class="form-group">
						{{ form.gender.label_tag }}
						{{ form.gender }}
						<p class="error no-margin-bottom">
							{% for error in form.gender.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-odd text-center">
					<div class="form-group">
						{{ form.personal_text.label_tag }}
						{{ form.personal_text }}
						<p class="error no-margin-bottom">
							{% for error in form.personal_text.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center">
					<div class="form-group">
						{{ form.signature.label_tag }}
						{{ form.signature }}
						<p class="error no-margin-bottom">
							{% for error in form.signature.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-odd text-center">
					<div class="form-group">
						<label for="id_avatar">Picture:</label>
						{{ form.avatar }}
						<p class="error no-margin-bottom">
							{% for error in form.avatar.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center">
					<div class="form-group">
						{{ form.website_title.label_tag }}
						{{ form.website_title }}
						<p class="error no-margin-bottom">
							{% for error in form.website_title.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-odd text-center">
					<div class="form-group">
						{{ form.website_url.label_tag }}
						{{ form.website_url }}
						<p class="error no-margin-bottom">
							{% for error in form.website_url.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center">
					<div class="form-group">
						{{ form.location.label_tag }}
						{{ form.location }}
						<p class="error no-margin-bottom">
							{% for error in form.location.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-odd text-center">
					<div class="form-group">
						{{ form.yim.label_tag }}
						{{ form.yim }}
						<p class="error no-margin-bottom">
							{% for error in form.yim.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center">
					<div class="form-group">
						{{ form.twitter.label_tag }}
						{{ form.twitter }}
						<p class="error no-margin-bottom">
							{% for error in form.twitter.errors %} {{ error }} {% endfor %}
						</p>
					</div>
				</div>
				<div class="board-content board-content-even text-center board-content-last">
					<a href="{% url 'send_confirmation_email_for_account_deactivation' %}">
						Deactivate Account
					</a>
				</div>
				<div class="form-group">
					<input type="submit" value="Update Profile">
				</div>
			</form>
		</div>
	</div>
{% endblock %}

userprofile/templates/send_confirmation_email_for_account_deactivation.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  	<h2>Deactivate account</h2>
		  	<h6>A CONFIRMATION EMAIL NEEDS TO BE SENT TO YOUR EMAIL ADDRESS.</h6>
		  	<a href="{% url 'do_confirmation_email_for_account_deactivation' %}">Send Confirmation Email</a>
		</div>
	</div>
{% endblock %}

userprofile/templates/send_mail_to_supermod.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load add_class_tags %}
{% block content %}
	<div class="container-fluid">
		<div class="row">
		  	<div class="featured-content">
				<form action="{% url 'send_mail_to_supermod' board_id %}" method="post" class="no-margin-bottom form-inline form-md send-mail-to-supermod"> 
					{% csrf_token %}
					<div class="form-group">
						{{ form.subject.label_tag }}
						<p>{{ form.subject }}</p>
						<p class="error no-margin-bottom">
							{% for error in form.subject.errors %} {{ error }} {% endfor %}
						</p>
					</div>
					<div class="form-group">
						{{ form.message.label_tag }}
						<p>{{ form.message }}</p>
						<p class="error no-margin-bottom">
							{% for error in form.message.errors %} {{ error }} {% endfor %}
						</p>
					</div>
					<div class="form-group">
						<p><input type="submit" value="Submit"></p>
					</div>
				</form>	  		
		  	</div>
		</div>
	</div>
{% endblock %}